# Generated by Django 5.2 on 2025-05-09 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BjHouse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "jianjie",
                    models.CharField(max_length=100, null=True, verbose_name="简介"),
                ),
                (
                    "xiaoqu",
                    models.CharField(max_length=100, null=True, verbose_name="小区"),
                ),
                (
                    "huxing",
                    models.CharField(max_length=100, null=True, verbose_name="户型"),
                ),
                ("mianji", models.FloatField(null=True, verbose_name="面积")),
                (
                    "guanzhurenshu",
                    models.IntegerField(null=True, verbose_name="关注人数"),
                ),
                (
                    "guankancishu",
                    models.IntegerField(null=True, verbose_name="观看次数"),
                ),
                (
                    "fabushijian",
                    models.CharField(
                        max_length=100, null=True, verbose_name="发布时间"
                    ),
                ),
                ("fangjia", models.FloatField(null=True, verbose_name="房价")),
                ("danjia", models.IntegerField(null=True, verbose_name="单价/平")),
                (
                    "chengqu",
                    models.CharField(max_length=100, null=True, verbose_name="城区"),
                ),
                ("jingdu", models.FloatField(null=True, verbose_name="经度")),
                ("weidu", models.FloatField(null=True, verbose_name="纬度")),
            ],
        ),
        migrations.CreateModel(
            name="YourModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("age", models.IntegerField(verbose_name="年龄")),
            ],
        ),
        migrations.CreateModel(
            name="UserViewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_time", models.DateTimeField(auto_now_add=True)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="new01.bjhouse"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-view_time"],
            },
        ),
    ]
